- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: debian.yml
  when: ansible_distribution == "Debian"

- include: amazon.yml
  when: ansible_distribution == "Amazon"

#####################
# Common
- name: "Ensure the collectd exec module directory exists"
  file: >
    path=/opt/collectd-exec-modules
    state=directory
  tags:
    - collectd
    - pkgs
    - libs

- name: "Make sure /etc/collectd.d is present"
  file: >
    path=/etc/collectd.d
    state=directory
  tags:
    - collectd
    - files
    - configs

- name: "Upload plugin configs"
  template: >
    src=plugin-configs/{{ item }}.conf.j2
    dest={{ collectd_d_config_dir }}/{{ item }}.conf
    mode=0644
  with_items: "{{ collectd_plugins }}"
  notify:
    - Restart collectd
  tags:
    - collectd
    - files
    - configs

- name: "Install coretemp plugin for collectd"
  copy: >
    src=collectd-coretemp.sh
    dest=/opt/collectd-exec-modules/
    mode=0755
    owner=root
    group=root
  notify:
    - Restart collectd
  tags:
    - collectd
    - files

- name: "Install /etc/collectd.conf"
  template: >
    src=collectd.conf.j2
    dest={{ collectd_config_dest }}
    mode=0644
  notify:
    - Restart collectd
  tags:
    - collectd
    - files
    - configs

- name: "Add the coretemp kernel module"
  modprobe: >
    name=coretemp
    state=present
  when: monitor_coretemp
  tags:
    - collectd
    - files
    - configs

- name: "Make sure collectd is running"
  service: >
    name=collectd
    state=started
    enabled=yes
    runlevel=5
  tags:
    - collectd
